import React, { useMemo, useState } from 'react';
import { createRoot } from 'react-dom/client';
import './styles.css';

const roleMeta = {
  public:{label:'Public User', eyebrow:'PUBLIC PORTAL', desc:'Pelapor membuat pengaduan, memantau progress, upload bukti, menjawab klarifikasi, dan menerima/menolak resolusi.', tabs:['Dashboard','Pengaduan Saya','Buat Pengaduan','Notifikasi','Profil']},
  platform:{label:'Platform / Pialang', eyebrow:'MEMBER PORTAL', desc:'Menangani kasus yang menjadi current owner platform/pialang saja.', tabs:['Dashboard','Case Queue','Reporting']},
  bursa:{label:'Bursa', eyebrow:'BURSA OVERSIGHT', desc:'Oversight level di atas platform untuk review, eskalasi, dan monitoring kinerja platform.', tabs:['Dashboard','Case Queue','Platform Performance']},
  kliring:{label:'Kliring', eyebrow:'CLEARING PORTAL', desc:'Menangani kasus settlement, withdrawal log, clearing, dan rekonsiliasi.', tabs:['Dashboard','Settlement Queue','Evidence Review']},
  regulator:{label:'Bappebti Regulator', eyebrow:'REGULATOR CONSOLE', desc:'Monitor kasus Bappebti-owned, member-assigned, critical queue, dan public feedback.', tabs:['Executive Dashboard','Complaint Queue','Kritik / Masukan','Member Performance','Reporting']},
  association:{label:'Association', eyebrow:'ASSOCIATION VIEW', desc:'Melihat tren industri dan insight edukasi tanpa data pribadi pelapor.', tabs:['Dashboard','Trend Insight','Education Topics']},
  admin:{label:'Super Admin', eyebrow:'SYSTEM ADMIN', desc:'Master data, role, SLA, workflow routing, dan audit trail sistem.', tabs:['Dashboard','User Management','Master Data','SLA Config','Audit Logs']}
};

const members=[
  {name:'PT Bursa Digital Nusantara', type:'Platform/Pialang', bursa:'Bursa Berjangka Jakarta', kliring:'PT Kliring Berjangka Indonesia', total:42, active:17, handled:25, unhandled:6, overdue:8, critical:6, avg:'3.8 hari', risk:'High'},
  {name:'PT Indodax Nasional Indonesia', type:'Pedagang Aset Kripto', bursa:'PT Bursa Komoditi Nusantara', kliring:'PT Kliring Komoditi Digital', total:25, active:9, handled:16, unhandled:2, overdue:3, critical:2, avg:'2.1 hari', risk:'Medium'},
  {name:'PT Crypto Indonesia Berkat', type:'Pedagang Aset Kripto', bursa:'PT Bursa Komoditi Nusantara', kliring:'PT Kliring Komoditi Digital', total:31, active:14, handled:17, unhandled:7, overdue:6, critical:5, avg:'4.4 hari', risk:'High'},
  {name:'PT Pintu Kemana Saja', type:'Pedagang Aset Kripto', bursa:'PT Bursa Komoditi Nusantara', kliring:'PT Kliring Komoditi Digital', total:18, active:6, handled:12, unhandled:1, overdue:2, critical:1, avg:'2.6 hari', risk:'Low'},
  {name:'PT Monex Investindo Futures', type:'Pialang Berjangka', bursa:'Bursa Berjangka Jakarta', kliring:'PT Kliring Berjangka Indonesia', total:12, active:4, handled:8, unhandled:1, overdue:1, critical:0, avg:'1.9 hari', risk:'Low'}
];

const cases=[
  {id:'BPP-2026-000184', title:'Penarikan dana belum diterima', user:'Andi Pratama', platform:'PT Bursa Digital Nusantara', bursa:'Bursa Berjangka Jakarta', kliring:'PT Kliring Berjangka Indonesia', category:'Dana / Withdrawal', sub:'Withdrawal belum masuk rekening', status:'In Progress', severity:'High', currentOwnerType:'platform', currentOwner:'PT Bursa Digital Nusantara', responsibility:'Member Assigned', queue:'Member Queue', sla:'18 jam tersisa', submitted:'12 Jun 2026 09:18', updated:'12 Jun 2026 14:05', incident:'10 Jun 2026', ref:'WD-8839201', account:'ANDI-8821', amount:'Rp 27.500.000', expected:'Dana diterima atau bukti settlement resmi.', risk:'Nilai transaksi material. Perlu bukti settlement, withdrawal log, dan audit trail approval.', evidence:['Bukti transfer.pdf','Screenshot status withdrawal.png'], timeline:[['12 Jun 2026 09:18','Public User','Complaint submitted','Pengaduan dikirim melalui BAPPEBTI PORTAL.'],['12 Jun 2026 09:21','System','Validation completed','Data wajib dan bukti awal lengkap.'],['12 Jun 2026 09:24','System','Assigned to Platform','Current owner: PT Bursa Digital Nusantara.'],['12 Jun 2026 14:05','Platform','Investigation started','Platform memeriksa withdrawal log dan settlement status.']]},
  {id:'BPP-2026-000185', title:'Transaksi tidak dikenali pada akun', user:'Sari Wulandari', platform:'PT Crypto Indonesia Berkat', bursa:'PT Bursa Komoditi Nusantara', kliring:'PT Kliring Komoditi Digital', category:'Transaksi Tidak Dikenali', sub:'Unauthorized transaction', status:'Regulator Review', severity:'Critical', currentOwnerType:'regulator', currentOwner:'Direktorat Pengawasan PBK', responsibility:'Bappebti Owned', queue:'Critical Queue', sla:'Overdue 4 jam', submitted:'11 Jun 2026 16:45', updated:'12 Jun 2026 10:15', incident:'11 Jun 2026', ref:'TRX-22190888', account:'SARI-7712', amount:'Tidak diisi', expected:'Investigasi resmi atas transaksi tidak dikenali.', risk:'Indikasi fraud dan potensi pola berulang. Perlu review regulator.', evidence:['Log aktivitas akun.xlsx','Email notifikasi transaksi.pdf'], timeline:[['11 Jun 2026 16:45','Public User','Complaint submitted','Kasus masuk dengan indikasi transaksi tidak dikenali.'],['11 Jun 2026 17:00','System','High risk detected','Kategori dan kata kunci masuk risk trigger.'],['12 Jun 2026 08:40','Platform','Initial response disputed','Jawaban awal platform ditolak pelapor.'],['12 Jun 2026 10:15','Bappebti','Escalation accepted','Current owner berubah ke regulator.']]},
  {id:'BPP-2026-000186', title:'Saldo aset tidak sesuai setelah settlement', user:'Michael Tan', platform:'PT Pintu Kemana Saja', bursa:'PT Bursa Komoditi Nusantara', kliring:'PT Kliring Komoditi Digital', category:'Settlement / Kliring', sub:'Perbedaan saldo setelah settlement', status:'Settlement Review', severity:'Medium', currentOwnerType:'kliring', currentOwner:'PT Kliring Komoditi Digital', responsibility:'Member Assigned', queue:'Kliring Queue', sla:'9 jam tersisa', submitted:'12 Jun 2026 10:22', updated:'12 Jun 2026 12:41', incident:'12 Jun 2026', ref:'SETTLE-66201', account:'MIKE-2020', amount:'Rp 8.200.000', expected:'Koreksi saldo sesuai hasil settlement.', risk:'Terkait batch settlement dan rekonsiliasi; current owner adalah kliring.', evidence:['Riwayat transaksi.csv'], timeline:[['12 Jun 2026 10:22','Public User','Complaint submitted','Pelapor menyampaikan selisih saldo aset.'],['12 Jun 2026 10:28','System','Assigned to Platform','Validasi awal selesai.'],['12 Jun 2026 12:10','Platform','Settlement dependency confirmed','Perlu review kliring.'],['12 Jun 2026 12:41','System','Assigned to Kliring','Current owner menjadi PT Kliring Komoditi Digital.']]},
  {id:'BPP-2026-000188', title:'Permintaan penutupan akun belum diproses', user:'Andi Pratama', platform:'PT Indodax Nasional Indonesia', bursa:'PT Bursa Komoditi Nusantara', kliring:'PT Kliring Komoditi Digital', category:'Akun / Penutupan Akun', sub:'Account closure request', status:'Resolution Proposed', severity:'Low', currentOwnerType:'public', currentOwner:'Andi Pratama', responsibility:'Waiting Public', queue:'User Action', sla:'24 jam tersisa', submitted:'10 Jun 2026 15:30', updated:'12 Jun 2026 11:00', incident:'09 Jun 2026', ref:'-', account:'ANDI-8821', amount:'Tidak relevan', expected:'Akun ditutup dan dikonfirmasi resmi.', risk:'Amount tidak relevan sehingga tidak perlu dipaksa diisi.', evidence:['Email permintaan penutupan.pdf'], timeline:[['10 Jun 2026 15:30','Public User','Complaint submitted','Permintaan penutupan akun dilaporkan.'],['10 Jun 2026 15:40','System','Assigned to Platform','Current owner menjadi platform.'],['12 Jun 2026 11:00','Platform','Resolution proposed','Platform mengajukan penyelesaian.'],['12 Jun 2026 11:05','System','Waiting public confirmation','Current owner kembali ke public user.']]}
];
const feedback=[{id:'FB-2026-0012',type:'Kritik',topic:'Alur registrasi',message:'Instruksi registrasi perlu dibuat lebih jelas untuk pengguna baru.',source:'Public Portal',status:'Open',date:'12 Jun 2026 13:20',owner:'Bappebti Service Desk'},{id:'FB-2026-0013',type:'Masukan',topic:'Notifikasi',message:'Pengguna meminta notifikasi email saat status pengaduan berubah.',source:'Public Portal',status:'Reviewed',date:'12 Jun 2026 14:05',owner:'Product Admin'}];

function App(){const[auth,setAuth]=useState(false),[role,setRole]=useState('public'),[tab,setTab]=useState('Dashboard'),[selected,setSelected]=useState(null),[selectedFeedback,setSelectedFeedback]=useState(null),[success,setSuccess]=useState(null),[step,setStep]=useState(1),[filters,setFilters]=useState({q:'',status:'All',severity:'All',resp:'All'}); const meta=roleMeta[role]; const visible=useMemo(()=>filterCases(scopeCases(role),filters),[role,filters]); function switchRole(r){setRole(r);setTab(roleMeta[r].tabs[0]);setSelected(null);setSelectedFeedback(null);setSuccess(null)} if(!auth)return <Auth onLogin={()=>setAuth(true)}/>; return <><header className="topbar"><div className="brandMark"><div className="logoMock">B</div><div><p>{meta.eyebrow}</p><h1>{meta.label}</h1><span>{meta.desc}</span></div></div><div className="tools"><button className="ghost">Help</button><button className="primary" onClick={()=>{setRole('public');setTab('Buat Pengaduan');setSelected(null)}}>+ Quick Action</button><select value={role} onChange={e=>switchRole(e.target.value)}>{Object.keys(roleMeta).map(k=><option key={k} value={k}>{roleMeta[k].label}</option>)}</select><button className="ghost square" onClick={()=>setAuth(false)}>↗</button></div></header><nav className="tabs">{meta.tabs.map(t=><button key={t} className={!selected&&!selectedFeedback&&!success&&tab===t?'active':''} onClick={()=>{setTab(t);setSelected(null);setSelectedFeedback(null);setSuccess(null)}}>{t}</button>)}</nav><main>{success?<Success data={success} open={()=>setSelected(cases[0])} another={()=>{setSuccess(null);setTab('Buat Pengaduan')}}/>:selected?<CaseDetail c={selected} role={role} back={()=>setSelected(null)}/>:selectedFeedback?<FeedbackDetail item={selectedFeedback} back={()=>setSelectedFeedback(null)}/>:<Router role={role} tab={tab} rows={visible} filters={filters} setFilters={setFilters} openCase={setSelected} openFeedback={setSelectedFeedback} step={step} setStep={setStep} submit={()=>{setSuccess({id:'BPP-2026-000201',currentOwner:'System Validation',time:'12 Jun 2026 17:48'});setStep(1)}}/>}</main></>}
function Auth({onLogin}){const[m,setM]=useState('login');return <div className="authPage"><div className="authHead"><div className="logoMock">B</div><div><b>Layanan Pengaduan Bappebti</b><span>Complaint Ecosystem Portal</span></div></div><section className="authGrid"><div className="hero"><p className="eyebrow">BAPPEBTI PORTAL</p><h2>Saluran pengaduan resmi yang transparan, terukur, dan dapat dipantau.</h2><p>Public user wajib register/login agar pengaduan valid, mengurangi spam, memiliki case ownership, dan dapat dimonitor sampai penyelesaian.</p><div className="flow"><span>Register / Login</span><b>›</b><span>Submit Complaint</span><b>›</b><span>Ticket Number</span><b>›</b><span>Track Resolution</span></div><div className="note"><b>Demo Scenario</b><p>Login sebagai Public User, buat pengaduan, lihat success ticket page, lalu gunakan role switcher kanan atas untuk melihat Platform, Bursa, Kliring, Regulator, Association, dan Admin.</p></div></div><div className="loginCard"><div className="switch"><button className={m==='login'?'active':''} onClick={()=>setM('login')}>Login</button><button className={m==='register'?'active':''} onClick={()=>setM('register')}>Register</button></div><h2>{m==='login'?'Masuk ke Portal':'Registrasi Akun'}</h2><label>Email<input defaultValue="andi.pratama@email.id"/></label>{m==='register'&&<><label>Nama Lengkap<input defaultValue="Andi Pratama"/></label><label>No. HP<input defaultValue="+62 812 0000 7711"/></label></>}<label>Password<input type="password" defaultValue="password"/></label><button className="primary full" onClick={onLogin}>{m==='login'?'Login Demo':'Register Demo'}</button></div></section></div>}
function Router(p){const{role,tab}=p;if(role==='public'&&tab==='Buat Pengaduan')return <Wizard {...p}/>; if(role==='public'&&tab==='Profil')return <Profile/>; if(role==='public'&&tab==='Notifikasi')return <Notifications openCase={p.openCase}/>; if(role==='regulator'&&tab==='Kritik / Masukan')return <FeedbackQueue open={p.openFeedback}/>; if(tab==='Member Performance'||tab==='Platform Performance')return <MemberPerformance/>; if(['User Management','Master Data','SLA Config','Audit Logs'].includes(tab))return <AdminPage tab={tab}/>; if(tab==='Reporting'||tab==='Trend Insight'||tab==='Education Topics')return <Reports role={role}/>; if(tab.includes('Queue')||tab==='Pengaduan Saya'||tab==='Settlement Queue'||tab==='Evidence Review')return <CaseQueue title={tab} {...p}/>; return <Dashboard role={role} openCase={p.openCase}/>}
function Dashboard({role,openCase}){if(role==='regulator')return <><Kpis items={[['Active Complaints','184','All open cases'],['Bappebti-Owned','31','Direct regulator responsibility'],['Member Assigned','129','Handled by platform/bursa/kliring'],['Critical Queue','17','High-risk cases','danger'],['SLA Breach','23','Past deadline','warn'],['Kritik / Masukan','42','Public feedback']]}/><div className="grid2"><Panel title="Queue Separation"><MiniTable rows={cases} openCase={openCase}/></Panel><Panel title="Risk & SLA Snapshot"><Bars rows={[['Withdrawal complaints',62],['Critical queue handled',43],['SLA compliance',76],['Member response',68]]}/></Panel></div></>; if(role==='admin')return <><Kpis items={[['Active Users','1,248','All roles'],['Members','82','Registered ecosystem'],['SLA Rules','16','Configured rules'],['Audit Logs','9,442','System changes']]}/><AdminPage tab="Dashboard"/></>; return <><Kpis items={role==='public'?[['Total Pengaduan','4','Submitted by user'],['In Progress','1','Being handled'],['Action Required','1','Need response','warn'],['Resolved','1','Closed cases']]:[['Current Owner Cases',scopeCases(role).length,'Assigned to this role only'],['Due Soon','4','Less than 24h','warn'],['Escalation Ready','2','Can escalate to Bappebti'],['Resolved Month','27','Closed cases']]}/><Panel title={role==='public'?'Recent Complaints':'Assigned Case List'}><MiniTable rows={scopeCases(role)} openCase={openCase}/></Panel></>}
function CaseQueue({title,rows,filters,setFilters,openCase,role}){return <Panel title={title}><div className="filters"><input placeholder="Search ticket, title, member" value={filters.q} onChange={e=>setFilters({...filters,q:e.target.value})}/><select value={filters.status} onChange={e=>setFilters({...filters,status:e.target.value})}><option>All</option><option>In Progress</option><option>Regulator Review</option><option>Settlement Review</option><option>Resolution Proposed</option></select><select value={filters.severity} onChange={e=>setFilters({...filters,severity:e.target.value})}><option>All</option><option>Low</option><option>Medium</option><option>High</option><option>Critical</option></select><select value={filters.resp} onChange={e=>setFilters({...filters,resp:e.target.value})}><option>All</option><option>Bappebti Owned</option><option>Member Assigned</option><option>Waiting Public</option></select><button className="ghost" onClick={()=>setFilters({q:'',status:'All',severity:'All',resp:'All'})}>Reset</button></div>{role==='regulator'&&<div className="legend"><b>Bappebti Owned</b> = regulator must act directly. <b>Member Assigned</b> = monitor SLA and intervene only if overdue/disputed/high-risk.</div>}<MiniTable rows={rows} openCase={openCase} showResp={role==='regulator'}/></Panel>}
function MiniTable({rows,openCase,showResp}){return <table className="table"><thead><tr><th>Ticket</th><th>Complaint</th><th>Member</th>{showResp&&<th>Responsibility</th>}<th>Status</th><th>Current Owner</th><th>SLA</th><th></th></tr></thead><tbody>{rows.map(c=><tr key={c.id}><td className="mono">{c.id}</td><td><b>{c.title}</b><span>{c.category}</span></td><td>{c.platform}</td>{showResp&&<td><span className={(c.responsibility==='Bappebti Owned'?'pill red':'pill')}>{c.responsibility}</span></td>}<td><span className="badge">{c.status}</span></td><td>{c.currentOwner}</td><td>{c.sla}</td><td><button className="ghost" onClick={()=>openCase(c)}>View</button></td></tr>)}</tbody></table>}
function MemberPerformance(){return <Panel title="Member Performance"><p className="sub">Daftar member/platform dengan jumlah kasus, kasus sudah ditangani, belum ditangani, SLA breach, critical cases, dan risk level.</p><table className="table"><thead><tr><th>Member</th><th>Type</th><th>Total Cases</th><th>Handled</th><th>Unhandled</th><th>SLA Breach</th><th>Critical</th><th>Avg Resolve</th><th>Risk</th></tr></thead><tbody>{members.map(m=><tr key={m.name}><td><b>{m.name}</b><span>{m.bursa} / {m.kliring}</span></td><td>{m.type}</td><td>{m.total}</td><td>{m.handled}</td><td>{m.unhandled}</td><td>{m.overdue}</td><td>{m.critical}</td><td>{m.avg}</td><td><span className={'severity '+m.risk.toLowerCase()}>{m.risk}</span></td></tr>)}</tbody></table></Panel>}
function FeedbackQueue({open}){return <Panel title="Kritik / Masukan Queue"><p className="sub">Dipisahkan dari complaint case. Bisa dibuka untuk review, assign owner, mark reviewed, atau convert menjadi formal complaint bila relevan.</p><table className="table"><thead><tr><th>ID</th><th>Type</th><th>Topic</th><th>Message</th><th>Owner</th><th>Status</th><th></th></tr></thead><tbody>{feedback.map(f=><tr key={f.id}><td className="mono">{f.id}</td><td>{f.type}</td><td><b>{f.topic}</b><span>{f.source}</span></td><td>{f.message}</td><td>{f.owner}</td><td><span className="badge">{f.status}</span></td><td><button className="ghost" onClick={()=>open(f)}>Open</button></td></tr>)}</tbody></table></Panel>}
function FeedbackDetail({item,back}){return <><button className="ghost" onClick={back}>← Back</button><Panel title={item.topic}><div className="compactGrid"><Info a="Feedback ID" b={item.id}/><Info a="Type" b={item.type}/><Info a="Source" b={item.source}/><Info a="Status" b={item.status}/><Info a="Owner" b={item.owner}/><Info a="Submitted" b={item.date}/></div><div className="note"><b>Message</b><p>{item.message}</p></div><div className="actionBar"><button className="ghost">Assign Owner</button><button className="ghost">Mark Reviewed</button><button className="ghost">Convert to Complaint</button><button className="primary">Close Feedback</button></div></Panel></>}
function CaseDetail({c,role,back}){const actions=getActions(role,c);return <><button className="ghost" onClick={back}>← Back</button><section className="detailHead"><div><p className="mono">{c.id}</p><h2>{c.title}</h2><span className="memberTag">{c.platform}</span></div><div><span className={'severity '+c.severity.toLowerCase()}>{c.severity}</span><span className="badge">{c.responsibility}</span><span className="badge">{c.status}</span></div></section><div className="gridDetail"><Panel title="Case Information"><div className="compactGrid"><Info a="Platform" b={c.platform}/><Info a="Category" b={c.category}/><Info a="Sub Category" b={c.sub}/><Info a="Platform User ID" b={c.account}/><Info a="Transaction Ref" b={c.ref}/><Info a="Incident Date" b={c.incident}/><Info a="Amount" b={c.amount}/><Info a="Channel" b="BAPPEBTI PORTAL"/><Info a="Expected Resolution" b={c.expected}/></div><div className="risk"><b>Risk Note</b><p>{c.risk}</p></div><h3>Vertical Case Timeline</h3><ul className="timeline">{c.timeline.map((t,i)=><li key={i}><i></i><div><time>{t[0]}</time><b>{t[2]}</b><span>{t[1]}</span><p>{t[3]}</p></div></li>)}</ul></Panel><aside><Panel title="Ownership & Actions"><div className="owner"><span>Current Owner</span><b>{c.currentOwner}</b><small>{c.currentOwnerType.toUpperCase()} only. Ownership is singular, not simultaneous.</small></div><h3>Evidence</h3>{c.evidence.map(e=><p className="doc" key={e}>▣ {e}</p>)}<h3>Available Actions for {roleMeta[role].label}</h3>{actions.map(a=><button key={a} className={a.includes('Update')||a.includes('Assign')?'primary full':'ghost full'}>{a}</button>)}</Panel></aside></div></>}
function getActions(role,c){if(role==='public')return c.status==='Resolution Proposed'?['Accept Resolution','Reject Resolution','Upload Additional Evidence']:['Upload Additional Evidence','Reply Clarification','Request Escalation']; if(role==='platform')return ['Add Investigation Note','Request Clarification to User','Upload Handling Evidence','Propose Resolution','Escalate to Bursa / Bappebti']; if(role==='bursa')return ['Review Platform Handling','Ask Platform Follow-up','Assign to Kliring','Escalate to Bappebti']; if(role==='kliring')return ['Upload Settlement Proof','Request Platform Data','Return to Platform','Escalate to Bappebti']; if(role==='regulator')return ['Assign / Re-assign Owner','Take Over as Bappebti-Owned','Request Member Explanation','Close / Reopen Case']; if(role==='admin')return ['View Audit Trail','Correct Master Mapping']; return ['View Aggregated Detail'];}
function Wizard({step,setStep,submit}){const sections=[['Complaint Summary',[['Complaint Title','Penarikan dana belum diterima'],['Platform','PT Bursa Digital Nusantara'],['Category / Sub','Dana / Withdrawal - Withdrawal belum masuk rekening'],['Urgency','High']]],['Reference Detail',[['Platform User ID','ANDI-8821'],['Transaction Ref','WD-8839201'],['Incident Date','10 Jun 2026'],['Amount','Rp 27.500.000 (Optional)']]],['Resolution & Routing',[['Expected Resolution','Dana diterima atau bukti settlement resmi'],['Evidence','2 files uploaded'],['Channel','BAPPEBTI PORTAL'],['Routing Preview','Platform → Bursa → Kliring']]]];return <Panel title="Buat Pengaduan Baru" eyebrow="PUBLIC USER SUBMISSION"><div className="steps">{[1,2,3,4].map(n=><span key={n} className={step===n?'active':''}>{n}</span>)}</div>{step<4&&<WizardForm step={step}/>} {step===4&&<div className="confirmPage">{sections.map(([title,items])=><section key={title}><h3>{title}</h3><div className="compactGrid">{items.map(([a,b])=><Info key={a} a={a} b={b}/>)}</div></section>)}<div className="note"><b>Final Declaration</b><p>Pastikan data sudah benar. Ticket number akan dibuat setelah pengaduan dikirim dan dapat dipantau dari dashboard.</p></div><label className="check"><input type="checkbox" defaultChecked/> Saya menyatakan informasi dan bukti yang disampaikan benar.</label></div>}<div className="navBtns"><button className="ghost" disabled={step===1} onClick={()=>setStep(step-1)}>Previous</button><button className="primary" onClick={()=>step===4?submit():setStep(step+1)}>{step===4?'Submit Complaint':'Next'}</button></div></Panel>}
function WizardForm({step}){if(step===1)return <div className="formGrid">{['Nama Pelapor','Email Terdaftar','No. HP','Platform User ID','Domisili','NIK / Identitas'].map(f=><Field key={f} name={f}/>)}</div>; if(step===2)return <div className="formGrid">{['Judul Pengaduan','Kategori','Sub-Kategori','Platform / Member','Tanggal Kejadian','Referensi Transaksi','Amount (Optional)','Urgensi','Ekspektasi Penyelesaian'].map(f=><Field key={f} name={f}/>)}</div>; return <><label className="textLabel">Kronologi<textarea defaultValue="Pada tanggal 10 Jun 2026 saya melakukan penarikan dana, namun dana belum masuk ke rekening."/></label><div className="uploadBox">Upload evidence: bukti transfer, screenshot, email, chat, log transaksi</div></>}
function Success({data,open,another}){return <Panel><div className="success"><div className="bigIcon">✓</div><h2>Pengaduan berhasil dikirim</h2><p>Ticket number telah dibuat dan dapat dipantau melalui dashboard pengguna.</p><div className="ticket"><span>Ticket Number</span><b>{data.id}</b></div><div className="compactGrid"><Info a="Status" b="Submitted"/><Info a="Current Owner" b={data.currentOwner}/><Info a="Submitted Time" b={data.time}/><Info a="Expected First Response" b="1 x 24 jam"/><Info a="Channel" b="BAPPEBTI PORTAL"/><Info a="Next Step" b="Validasi dan routing awal"/></div><div className="centerBtns"><button className="primary" onClick={open}>View Case Detail</button><button className="ghost" onClick={another}>Create Another Complaint</button></div></div></Panel>}
function Notifications({openCase}){return <Panel title="Notifikasi"><table className="table"><thead><tr><th>Time</th><th>Ticket</th><th>Notification</th><th>Action</th></tr></thead><tbody>{cases.slice(0,3).map(c=><tr key={c.id}><td>{c.updated}</td><td className="mono">{c.id}</td><td><b>{c.status}</b><span>{c.title}</span></td><td><button className="ghost" onClick={()=>openCase(c)}>Open Ticket</button></td></tr>)}</tbody></table></Panel>}
function Profile(){return <Panel title="Profil Saya"><div className="compactGrid"><Info a="Nama" b="Andi Pratama"/><Info a="NIK" b="3273********0001"/><Info a="Email" b="andi.pratama@email.id"/><Info a="No. HP" b="+62 812 **** 7711"/><Info a="Domicile" b="Jakarta Selatan"/><Info a="Registered" b="01 Jun 2026"/></div><h3>Security & Preferences</h3><p className="doc">✓ Email notification enabled</p><p className="doc">✓ WhatsApp notification enabled</p><p className="doc">✓ Password last changed 7 days ago</p></Panel>}
function AdminPage({tab}){const data={Dashboard:[['Role Matrix','Public, Platform, Bursa, Kliring, Regulator, Association, Admin'],['Workflow Rule','Current owner is singular and changes through assignment'],['Audit Trail','Every status, assignment, evidence, and decision is logged']], 'User Management':[['Public Users','1,120 registered users'],['Member Users','82 member accounts'],['Regulator Users','24 internal users']], 'Master Data':[['Platform Mapping','Platform mapped to Bursa and Kliring'],['Member Status','Active / Suspended / Under Review'],['Routing Rule','By category, platform, severity, and owner']], 'SLA Config':[['High Severity','1 x 24 jam first response'],['Critical','4 jam first response + regulator alert'],['Escalation','Auto-escalate when overdue/disputed']], 'Audit Logs':[['12 Jun 2026 14:05','Platform started investigation'],['12 Jun 2026 12:41','System assigned case to Kliring'],['12 Jun 2026 10:15','Bappebti accepted escalation']]};return <Panel title={tab}><div className="compactGrid">{(data[tab]||data.Dashboard).map(([a,b])=><Info key={a} a={a} b={b}/>)}</div></Panel>}
function Reports({role}){return <Panel title="Reporting"><div className="grid2"><div><h3>Dashboard / Reporting Features</h3><Bars rows={role==='regulator'?[['SLA Compliance',76],['Member Response',68],['Critical Closed',43],['Public Satisfaction',82]]:[['Complaint Trend',62],['Resolved Cases',75],['Due Soon',35],['Education Need',58]]}/></div><div><h3>Sample Reports</h3>{['Executive Summary Report','SLA Compliance Report','Member Performance Report','Risk & Fraud Pattern Report','Public Feedback Report'].map(x=><p className="doc" key={x}>▣ {x}</p>)}</div></div></Panel>}
function Kpis({items}){return <section className="kpis">{items.map(([a,b,c,t])=><div className={'kpi '+(t||'')} key={a}><span>{a}</span><b>{b}</b><p>{c}</p></div>)}</section>}
function Bars({rows}){return <div className="bars">{rows.map(([n,v])=><div key={n}><span>{n}</span><div><i style={{width:v+'%'}}/></div><b>{v}%</b></div>)}</div>}
function Panel({title,eyebrow,children}){return <section className="panel">{eyebrow&&<p className="eyebrow">{eyebrow}</p>}{title&&<h2>{title}</h2>}{children}</section>}
function Info({a,b}){return <div className="mini"><span>{a}</span><b>{b}</b></div>}
function Field({name}){return <label>{name}<input defaultValue={sample(name)}/></label>}
function sample(f){if(f.includes('Nama'))return'Andi Pratama';if(f.includes('Email'))return'andi.pratama@email.id';if(f.includes('HP'))return'+62 812 0000 7711';if(f.includes('Platform User'))return'ANDI-8821';if(f.includes('Domisili'))return'Jakarta Selatan';if(f.includes('NIK'))return'3273********0001';if(f.includes('Judul'))return'Penarikan dana belum diterima';if(f==='Kategori')return'Dana / Withdrawal';if(f.includes('Sub'))return'Withdrawal belum masuk rekening';if(f.includes('Platform'))return'PT Bursa Digital Nusantara';if(f.includes('Tanggal'))return'10 Jun 2026';if(f.includes('Referensi'))return'WD-8839201';if(f.includes('Amount'))return'Rp 27.500.000';if(f.includes('Urgensi'))return'High';return'Dana diterima atau bukti settlement resmi'}
function scopeCases(role){if(role==='public')return cases.filter(c=>c.user==='Andi Pratama');if(role==='platform')return cases.filter(c=>c.currentOwnerType==='platform');if(role==='bursa')return cases.filter(c=>c.currentOwnerType==='bursa'||c.severity==='High'||c.severity==='Critical');if(role==='kliring')return cases.filter(c=>c.currentOwnerType==='kliring'||c.category.includes('Settlement'));return cases}
function filterCases(rows,f){const q=f.q.toLowerCase();return rows.filter(c=>(!q||[c.id,c.title,c.platform,c.category,c.currentOwner,c.responsibility].join(' ').toLowerCase().includes(q))&&(f.status==='All'||c.status===f.status)&&(f.severity==='All'||c.severity===f.severity)&&(f.resp==='All'||c.responsibility===f.resp))}

createRoot(document.getElementById('root')).render(<App/>);
