import React, { useMemo, useState } from "react";
import { createRoot } from "react-dom/client";
import { motion } from "framer-motion";
import {
  AlertCircle,
  ArrowLeft,
  ArrowRight,
  CheckCircle2,
  ChevronDown,
  ClipboardCheck,
  Clock3,
  Download,
  Eye,
  FileText,
  HelpCircle,
  Info,
  LockKeyhole,
  Mail,
  MessageCircle,
  Paperclip,
  Phone,
  Search,
  ShieldCheck,
  UploadCloud,
} from "lucide-react";
import "./index.css";

const NAV = ["Beranda", "Profil", "Peraturan", "Pelaku Pasar", "Informasi Publik", "Berita", "Kontak"];
const STEPS = ["Jenis Layanan", "Identitas Pelapor", "Detail Pengaduan", "Bukti Pendukung", "Tinjau & Kirim", "Status Pengaduan"];
const sampleTimeline = [
  { title: "Pengaduan diterima", note: "Nomor tiket BPP-2026-000184 telah diterbitkan dan bukti pengaduan dikirim ke email pelapor.", time: "20 Mei 2026, 08:12 WIB", done: true },
  { title: "Verifikasi awal Bappebti", note: "Petugas melakukan validasi kelengkapan data, kategori, dan kewenangan penanganan.", time: "20 Mei 2026, 09:05 WIB", done: true },
  { title: "Diteruskan ke pelaku usaha terkait", note: "Pengaduan telah dikirim ke PIC platform untuk investigasi dan tanggapan resmi.", time: "20 Mei 2026, 10:42 WIB", done: true },
  { title: "Menunggu tanggapan pelaku usaha", note: "Platform wajib memberikan tanggapan awal sesuai SLA yang ditentukan.", time: "Sisa waktu 18 jam", done: false },
  { title: "Validasi penyelesaian", note: "Bappebti dan pelapor akan memvalidasi tindak lanjut sebelum tiket ditutup.", time: "Belum dimulai", done: false },
];

function Badge({ children, tone = "blue" }) {
  const map = {
    blue: "bg-[#0b3042] text-white",
    pale: "bg-[#eef4f6] text-[#0b3042] border border-[#d7e4e8]",
    green: "bg-emerald-50 text-emerald-700 border border-emerald-200",
    amber: "bg-amber-50 text-amber-800 border border-amber-200",
    red: "bg-rose-50 text-rose-700 border border-rose-200",
  };
  return <span className={`inline-flex items-center rounded-sm px-3 py-1 text-xs font-medium tracking-wide ${map[tone]}`}>{children}</span>;
}

function Header({ setPage }) {
  return (
    <header className="sticky top-0 z-40 border-b border-zinc-200 bg-white/95 backdrop-blur">
      <div className="mx-auto flex max-w-7xl items-center justify-between px-6 py-3">
        <button onClick={() => setPage("landing")} className="flex items-center gap-3 text-left">
          <div className="relative h-12 w-12 overflow-hidden rounded-sm bg-white">
            <div className="absolute left-1 top-2 h-8 w-10 rounded-full border-[5px] border-[#1f7fa0] border-r-transparent border-b-transparent rotate-[-18deg]" />
            <div className="absolute left-3 top-0 h-11 w-8 rounded-full border-[4px] border-[#6aa84f] border-l-transparent border-b-transparent rotate-[20deg]" />
            <div className="absolute left-1 top-7 h-[4px] w-10 bg-[#1f7fa0] rotate-[10deg]" />
          </div>
          <div className="leading-tight">
            <p className="text-[13px] font-semibold uppercase tracking-wider text-zinc-700">Kementerian</p>
            <p className="text-[13px] font-semibold uppercase tracking-wider text-zinc-700">Perdagangan</p>
            <p className="text-[10px] uppercase tracking-wider text-zinc-500">Republik Indonesia</p>
          </div>
        </button>
        <nav className="hidden items-center gap-8 lg:flex">
          {NAV.map((item) => <button key={item} className="flex items-center gap-1 text-[15px] text-zinc-700 hover:text-[#0b3042]">{item}{["Profil", "Peraturan", "Pelaku Pasar", "Informasi Publik", "Berita"].includes(item) && <ChevronDown className="h-3.5 w-3.5" />}</button>)}
        </nav>
        <button onClick={() => setPage("tracking")} className="rounded-sm border border-[#0b3042] px-4 py-2 text-xs font-semibold uppercase tracking-[0.16em] text-[#0b3042] hover:bg-[#0b3042] hover:text-white">Cek Status</button>
      </div>
    </header>
  );
}

function Footer() {
  return <footer className="mt-16 border-t border-zinc-200 bg-[#f5f5f5]"><div className="mx-auto grid max-w-7xl grid-cols-1 gap-8 px-6 py-10 md:grid-cols-4"><div className="md:col-span-2"><p className="text-sm font-semibold uppercase tracking-[0.2em] text-[#0b3042]">Bappebti</p><p className="mt-3 max-w-xl text-sm leading-6 text-zinc-600">Layanan Pengaduan Online untuk membantu masyarakat menyampaikan pengaduan, memantau tindak lanjut, dan menerima informasi status penanganan secara transparan.</p></div><div><p className="text-sm font-semibold text-zinc-800">Kontak Bantuan</p><div className="mt-3 space-y-2 text-sm text-zinc-600"><p className="flex items-center gap-2"><Phone className="h-4 w-4" /> 021-xxxx-xxxx</p><p className="flex items-center gap-2"><Mail className="h-4 w-4" /> layanan@bappebti.go.id</p></div></div><div><p className="text-sm font-semibold text-zinc-800">Jam Layanan</p><p className="mt-3 text-sm leading-6 text-zinc-600">Senin–Jumat<br />09.00–16.00 WIB</p></div></div></footer>;
}
function Layout({ children, setPage }) { return <div className="min-h-screen bg-[#f3f3f3] font-sans text-zinc-800"><Header setPage={setPage} />{children}<Footer /></div>; }
function HeroStat({ value, label }) { return <div className="border-l-4 border-[#0b3042] bg-[#f5f5f5] px-4 py-3"><p className="text-lg font-semibold text-[#0b3042]">{value}</p><p className="mt-1 text-xs leading-5 text-zinc-500">{label}</p></div>; }
function FlowItem({ number, title, text }) { return <div className="flex gap-4 border-b border-dashed border-zinc-200 pb-4 last:border-0 last:pb-0"><div className="flex h-10 w-10 shrink-0 items-center justify-center bg-[#0b3042] text-sm font-semibold text-white">{number}</div><div><p className="font-semibold text-zinc-800">{title}</p><p className="mt-1 text-sm leading-6 text-zinc-600">{text}</p></div></div>; }
function Hero({ setPage }) { return <section className="border-b border-zinc-200 bg-white"><div className="mx-auto grid max-w-7xl grid-cols-1 gap-10 px-6 py-12 lg:grid-cols-12 lg:py-16"><div className="lg:col-span-7"><Badge tone="pale">Layanan Pengaduan Online Bappebti</Badge><h1 className="mt-5 max-w-3xl text-4xl font-semibold leading-tight tracking-tight text-zinc-800 lg:text-5xl">Sampaikan pengaduan Anda secara resmi, mudah, dan terpantau.</h1><p className="mt-5 max-w-2xl text-base leading-7 text-zinc-600">Gunakan kanal ini untuk melaporkan kendala transaksi, layanan pelaku usaha, penarikan dana, akses akun, dugaan pelanggaran, atau permasalahan lain yang berada dalam ruang lingkup pengawasan Bappebti.</p><div className="mt-8 flex flex-wrap gap-3"><button onClick={() => setPage("service")} className="bg-[#0b3042] px-6 py-3 text-sm font-semibold uppercase tracking-[0.16em] text-white shadow-sm hover:bg-[#082638]">Buat Pengaduan</button><button onClick={() => setPage("tracking")} className="border border-zinc-300 bg-white px-6 py-3 text-sm font-semibold uppercase tracking-[0.16em] text-zinc-700 hover:border-[#0b3042] hover:text-[#0b3042]">Cek Status Tiket</button></div><div className="mt-8 grid max-w-2xl grid-cols-3 gap-4"><HeroStat value="1" label="Tiket resmi untuk setiap pengaduan" /><HeroStat value="SLA" label="Pemantauan batas waktu tindak lanjut" /><HeroStat value="Audit" label="Riwayat proses tercatat" /></div></div><div className="lg:col-span-5"><div className="border border-zinc-200 bg-[#f8f8f8] p-5 shadow-sm"><div className="bg-[#0b3042] px-5 py-4 text-white"><p className="text-sm font-medium tracking-[0.18em]">ALUR PENGADUAN</p></div><div className="space-y-4 bg-white p-5"><FlowItem number="01" title="Isi data pengaduan" text="Lengkapi identitas, platform terkait, kronologi, dan nilai transaksi bila ada." /><FlowItem number="02" title="Unggah bukti pendukung" text="Lampirkan bukti transaksi, screenshot, komunikasi, atau dokumen pendukung." /><FlowItem number="03" title="Verifikasi Bappebti" text="Petugas memeriksa kelengkapan dan menentukan arah penanganan." /><FlowItem number="04" title="Tindak lanjut pelaku usaha" text="Pengaduan diteruskan kepada pihak terkait dan dimonitor sampai selesai." /></div></div></div></div></section>; }
function Checklist({ text }) { return <div className="flex items-center gap-3 text-sm text-zinc-700"><CheckCircle2 className="h-5 w-5 text-[#1f7a5c]" />{text}</div>; }
function InfoCard({ icon: Icon, title, text, action, onClick }) { return <div className="border border-zinc-200 bg-white p-7 shadow-sm"><div className="mb-5 flex h-14 w-14 items-center justify-center rounded-full bg-[#0b3042] text-white"><Icon className="h-7 w-7" /></div><h3 className="text-xl font-semibold text-zinc-800">{title}</h3><p className="mt-3 min-h-[72px] text-sm leading-6 text-zinc-600">{text}</p><button onClick={onClick} className="mt-6 inline-flex items-center gap-2 text-sm font-semibold uppercase tracking-[0.16em] text-[#0b3042]">{action} <ArrowRight className="h-4 w-4" /></button></div>; }
function Landing({ setPage }) { return <Layout setPage={setPage}><Hero setPage={setPage} /><main className="mx-auto max-w-7xl px-6 py-12"><div className="grid grid-cols-1 gap-7 lg:grid-cols-3"><InfoCard icon={ClipboardCheck} title="Pengaduan Formal" text="Untuk keluhan yang membutuhkan verifikasi, nomor tiket, tindak lanjut, SLA, dan hasil penanganan." action="Mulai pengaduan" onClick={() => setPage("service")} /><InfoCard icon={MessageCircle} title="Kritik & Saran" text="Untuk masukan layanan, ide perbaikan, atau laporan umum yang tidak membutuhkan penanganan kasus formal." action="Kirim masukan" onClick={() => setPage("suggestion")} /><InfoCard icon={Search} title="Cek Status" text="Masukkan nomor tiket dan email/no. HP untuk melihat perkembangan penanganan pengaduan Anda." action="Cek status" onClick={() => setPage("tracking")} /></div><div className="mt-10 grid grid-cols-1 gap-7 lg:grid-cols-12"><div className="border border-zinc-200 bg-white p-7 lg:col-span-7"><h2 className="text-2xl font-semibold text-zinc-800">Sebelum membuat pengaduan</h2><p className="mt-3 text-sm leading-7 text-zinc-600">Pastikan pengaduan berisi kronologi yang jelas, identitas pelapor yang dapat dihubungi, nama pelaku usaha/platform terkait, serta bukti pendukung agar proses verifikasi dapat dilakukan lebih cepat.</p><div className="mt-6 grid grid-cols-1 gap-4 md:grid-cols-2"><Checklist text="Sudah menghubungi pihak platform terkait" /><Checklist text="Memiliki bukti transaksi atau nomor referensi" /><Checklist text="Mengetahui tanggal kejadian dan nominal" /><Checklist text="Menggunakan email/nomor HP aktif" /></div></div><div className="border border-zinc-200 bg-white p-7 lg:col-span-5"><h2 className="text-2xl font-semibold text-zinc-800">Kategori umum</h2><div className="mt-5 space-y-3">{["Dana / Withdrawal", "Transaksi", "Akun / Akses", "Dugaan Penipuan", "Perilaku Pelaku Usaha", "Data Pribadi"].map((item) => <div key={item} className="flex items-center justify-between border border-zinc-200 px-4 py-3 text-sm text-zinc-700">{item}<ArrowRight className="h-4 w-4 text-[#0b3042]" /></div>)}</div></div></div></main></Layout>; }
function Stepper({ active }) { return <div className="mb-7 border border-zinc-200 bg-white p-5"><div className="grid grid-cols-2 gap-3 md:grid-cols-6">{STEPS.map((label, index) => { const current = index === active; const done = index < active; return <div key={label} className="flex items-center gap-3"><div className={`flex h-8 w-8 shrink-0 items-center justify-center rounded-full text-xs font-semibold ${done ? "bg-[#1f7a5c] text-white" : current ? "bg-[#0b3042] text-white" : "bg-zinc-100 text-zinc-400"}`}>{done ? <CheckCircle2 className="h-4 w-4" /> : index + 1}</div><p className={`hidden text-xs leading-4 md:block ${current ? "font-semibold text-[#0b3042]" : "text-zinc-500"}`}>{label}</p></div>})}</div></div>; }
function PageShell({ step, title, subtitle, children, setPage }) { return <Layout setPage={setPage}><main className="mx-auto max-w-7xl px-6 py-10"><div className="mb-6"><button onClick={() => setPage("landing")} className="mb-4 inline-flex items-center gap-2 text-sm text-zinc-500 hover:text-[#0b3042]"><ArrowLeft className="h-4 w-4" /> Kembali ke beranda</button><h1 className="text-3xl font-semibold tracking-tight text-zinc-800">{title}</h1><p className="mt-2 max-w-3xl text-sm leading-6 text-zinc-600">{subtitle}</p></div><Stepper active={step} />{children}</main></Layout>; }
function ServiceCard({ icon: Icon, title, text, points, onClick, recommended }) { return <button onClick={onClick} className="group border border-zinc-200 bg-white p-7 text-left shadow-sm transition hover:-translate-y-0.5 hover:border-[#0b3042] hover:shadow-md"><div className="flex items-start justify-between"><div className="flex h-14 w-14 items-center justify-center rounded-full bg-[#0b3042] text-white"><Icon className="h-7 w-7" /></div>{recommended && <Badge tone="amber">Disarankan</Badge>}</div><h2 className="mt-5 text-xl font-semibold text-zinc-800">{title}</h2><p className="mt-3 min-h-[96px] text-sm leading-6 text-zinc-600">{text}</p><div className="mt-5 space-y-2">{points.map((point) => <Checklist key={point} text={point} />)}</div><div className="mt-7 inline-flex items-center gap-2 text-sm font-semibold uppercase tracking-[0.16em] text-[#0b3042]">Pilih layanan <ArrowRight className="h-4 w-4 transition group-hover:translate-x-1" /></div></button>; }
function ServiceType({ setPage }) { return <PageShell setPage={setPage} step={0} title="Pilih jenis layanan" subtitle="Pilih kanal yang sesuai agar laporan Anda dapat diproses dengan tepat."><div className="grid grid-cols-1 gap-6 lg:grid-cols-3"><ServiceCard recommended icon={ClipboardCheck} title="Pengaduan Resmi" text="Untuk masalah yang membutuhkan nomor tiket, verifikasi Bappebti, tindak lanjut pelaku usaha, SLA, dan hasil penyelesaian." points={["Nomor tiket resmi", "Dapat dilacak", "Dapat diteruskan ke platform", "Memerlukan bukti pendukung"]} onClick={() => setPage("identity")} /><ServiceCard icon={MessageCircle} title="Kritik & Saran" text="Untuk masukan umum terkait layanan, informasi publik, atau perbaikan sistem yang tidak membutuhkan penanganan kasus formal." points={["Tidak selalu menjadi tiket formal", "Cocok untuk masukan layanan", "Tidak membutuhkan bukti transaksi", "Dapat dianalisis sebagai feedback"]} onClick={() => setPage("suggestion")} /><ServiceCard icon={HelpCircle} title="Butuh Bantuan Memilih?" text="Gunakan panduan singkat bila Anda belum yakin apakah laporan perlu masuk sebagai pengaduan formal atau kritik dan saran." points={["Panduan kategori", "Contoh kasus", "Estimasi data yang dibutuhkan", "Informasi kontak bantuan"]} onClick={() => setPage("guide")} /></div></PageShell>; }
function FormField({ label, placeholder, wide, helper, textarea, select }) { return <div className={wide ? "md:col-span-2" : ""}><label className="mb-2 block text-sm font-semibold text-zinc-700">{label}</label><div className="relative">{textarea ? <div className="min-h-[120px] border border-zinc-300 bg-white px-4 py-3 text-sm leading-6 text-zinc-500">{placeholder}</div> : <div className="border border-zinc-300 bg-white px-4 py-3 text-sm text-zinc-500">{placeholder}</div>}{select && <ChevronDown className="absolute right-3 top-3.5 h-4 w-4 text-zinc-400" />}</div>{helper && <p className="mt-1.5 text-xs leading-5 text-zinc-500">{helper}</p>}</div>; }
function SideHelp({ title, icon: Icon, items }) { return <aside className="lg:col-span-4"><div className="border border-zinc-200 bg-white p-6 shadow-sm"><div className="flex items-center gap-3"><div className="flex h-11 w-11 items-center justify-center rounded-full bg-[#0b3042] text-white"><Icon className="h-5 w-5" /></div><h2 className="text-lg font-semibold text-zinc-800">{title}</h2></div><div className="mt-5 space-y-4">{items.map((item) => <div key={item} className="flex gap-3 text-sm leading-6 text-zinc-600"><CheckCircle2 className="mt-0.5 h-5 w-5 shrink-0 text-[#1f7a5c]" />{item}</div>)}</div></div></aside>; }
function Identity({ setPage }) { return <PageShell setPage={setPage} step={1} title="Identitas pelapor" subtitle="Data ini digunakan untuk verifikasi dan pengiriman notifikasi status pengaduan."><div className="grid grid-cols-1 gap-7 lg:grid-cols-12"><div className="border border-zinc-200 bg-white p-7 lg:col-span-8"><div className="grid grid-cols-1 gap-5 md:grid-cols-2"><FormField label="Nama lengkap" placeholder="Masukkan nama sesuai identitas" /><FormField label="Nomor identitas" placeholder="NIK / Paspor / Identitas lain" /><FormField label="Email aktif" placeholder="nama@email.com" /><FormField label="Nomor HP / WhatsApp" placeholder="08xx-xxxx-xxxx" /><FormField label="Provinsi domisili" placeholder="Pilih provinsi" select /><FormField label="Kota/Kabupaten" placeholder="Pilih kota/kabupaten" select /></div><div className="mt-7 flex justify-between border-t border-zinc-200 pt-5"><button onClick={() => setPage("service")} className="border border-zinc-300 px-5 py-3 text-sm font-semibold uppercase tracking-[0.16em] text-zinc-600">Kembali</button><button onClick={() => setPage("complaint")} className="bg-[#0b3042] px-5 py-3 text-sm font-semibold uppercase tracking-[0.16em] text-white">Lanjutkan</button></div></div><SideHelp title="Privasi & keamanan" icon={LockKeyhole} items={["Data pelapor hanya digunakan untuk proses pengaduan.", "Notifikasi dikirim ke email/nomor HP yang terdaftar.", "Setiap perubahan status akan tercatat dalam riwayat tiket."]} /></div></PageShell>; }
function ComplaintDetail({ setPage }) { return <PageShell setPage={setPage} step={2} title="Detail pengaduan" subtitle="Isi informasi platform, kategori masalah, kronologi kejadian, dan data transaksi bila tersedia."><div className="grid grid-cols-1 gap-7 lg:grid-cols-12"><div className="border border-zinc-200 bg-white p-7 lg:col-span-8"><div className="grid grid-cols-1 gap-5 md:grid-cols-2"><FormField label="Nama pelaku usaha / platform" placeholder="Cari atau pilih nama platform" select helper="Sistem dapat melakukan pencocokan awal terhadap data pelaku usaha." /><FormField label="User ID / Nomor akun di platform" placeholder="Contoh: USR-884291" helper="Opsional, tetapi sangat membantu proses verifikasi." /><FormField label="Kategori pengaduan" placeholder="Dana / Withdrawal" select /><FormField label="Tingkat urgensi menurut pelapor" placeholder="Normal / Mendesak" select /><FormField label="Tanggal kejadian" placeholder="Pilih tanggal" /><FormField label="Nominal terkait" placeholder="Rp 0" /><FormField wide label="Nomor transaksi / referensi" placeholder="Masukkan nomor transaksi bila tersedia" /><FormField wide textarea label="Kronologi pengaduan" placeholder="Tuliskan kronologi dengan jelas: apa yang terjadi, kapan terjadi, pihak yang sudah dihubungi, dan respons terakhir dari platform." /></div><div className="mt-7 flex justify-between border-t border-zinc-200 pt-5"><button onClick={() => setPage("identity")} className="border border-zinc-300 px-5 py-3 text-sm font-semibold uppercase tracking-[0.16em] text-zinc-600">Kembali</button><button onClick={() => setPage("evidence")} className="bg-[#0b3042] px-5 py-3 text-sm font-semibold uppercase tracking-[0.16em] text-white">Lanjutkan</button></div></div><SideHelp title="Tips pengisian kronologi" icon={Info} items={["Gunakan urutan waktu yang jelas.", "Sebutkan nomor transaksi dan nominal bila ada.", "Jelaskan apakah sudah menghubungi pihak platform.", "Hindari memasukkan password atau PIN."]} /></div></PageShell>; }
function UploadedFile({ name, size, status }) { return <div className="flex items-center justify-between border border-zinc-200 bg-white px-4 py-3"><div className="flex items-center gap-3"><FileText className="h-5 w-5 text-[#0b3042]" /><div><p className="text-sm font-semibold text-zinc-800">{name}</p><p className="text-xs text-zinc-500">{size}</p></div></div><Badge tone="green">{status}</Badge></div>; }
function EvidenceUpload({ setPage }) { return <PageShell setPage={setPage} step={3} title="Bukti pendukung" subtitle="Unggah dokumen atau gambar yang dapat memperkuat pengaduan Anda."><div className="grid grid-cols-1 gap-7 lg:grid-cols-12"><div className="border border-zinc-200 bg-white p-7 lg:col-span-8"><div className="border-2 border-dashed border-zinc-300 bg-[#fafafa] px-8 py-12 text-center"><UploadCloud className="mx-auto h-12 w-12 text-[#0b3042]" /><h2 className="mt-4 text-xl font-semibold text-zinc-800">Tarik file ke sini atau pilih file</h2><p className="mt-2 text-sm text-zinc-500">Format: PDF, JPG, PNG. Maksimum 10MB per file.</p><button className="mt-6 border border-[#0b3042] px-5 py-3 text-sm font-semibold uppercase tracking-[0.16em] text-[#0b3042]">Pilih file</button></div><div className="mt-6 space-y-3"><UploadedFile name="bukti-withdrawal.png" size="1.2 MB" status="Berhasil diunggah" /><UploadedFile name="chat-customer-service.pdf" size="620 KB" status="Berhasil diunggah" /></div><div className="mt-7 flex justify-between border-t border-zinc-200 pt-5"><button onClick={() => setPage("complaint")} className="border border-zinc-300 px-5 py-3 text-sm font-semibold uppercase tracking-[0.16em] text-zinc-600">Kembali</button><button onClick={() => setPage("review")} className="bg-[#0b3042] px-5 py-3 text-sm font-semibold uppercase tracking-[0.16em] text-white">Tinjau Pengaduan</button></div></div><SideHelp title="Bukti yang disarankan" icon={Paperclip} items={["Screenshot transaksi atau withdrawal.", "Bukti transfer atau mutasi rekening.", "Riwayat komunikasi dengan platform.", "Dokumen pendukung lain yang relevan."]} /></div></PageShell>; }
function ReviewBlock({ title, rows }) { return <div className="border border-zinc-200 bg-white p-6"><h2 className="text-lg font-semibold text-zinc-800">{title}</h2><div className="mt-4 divide-y divide-zinc-100">{rows.map(([label, value], idx) => <div key={`${label}-${idx}`} className="grid grid-cols-12 gap-4 py-3 text-sm"><p className="col-span-4 font-medium text-zinc-500">{label}</p><p className="col-span-8 leading-6 text-zinc-800">{value}</p></div>)}</div></div>; }
function ReviewSubmit({ setPage }) { return <PageShell setPage={setPage} step={4} title="Tinjau & kirim pengaduan" subtitle="Periksa kembali data sebelum pengaduan dikirim ke Bappebti."><div className="grid grid-cols-1 gap-7 lg:grid-cols-12"><div className="space-y-5 lg:col-span-8"><ReviewBlock title="Identitas Pelapor" rows={[["Nama", "Andi Pratama"], ["Email", "andi@email.com"], ["No. HP", "0812-xxxx-xxxx"], ["Domisili", "DKI Jakarta"]]} /><ReviewBlock title="Detail Pengaduan" rows={[["Platform", "PT Bursa Digital Nusantara"], ["Kategori", "Dana / Withdrawal"], ["Nominal", "Rp 27.500.000"], ["Tanggal Kejadian", "17 Mei 2026"], ["Kronologi", "Dana penarikan belum diterima setelah 3 hari kerja dan belum ada estimasi penyelesaian dari platform."]]} /><ReviewBlock title="Bukti Pendukung" rows={[["File", "bukti-withdrawal.png"], ["File", "chat-customer-service.pdf"]]} /><div className="border border-amber-200 bg-amber-50 p-5 text-sm leading-6 text-amber-900"><p className="font-semibold">Pernyataan pelapor</p><p className="mt-1">Dengan mengirimkan pengaduan ini, pelapor menyatakan bahwa informasi yang diberikan benar dan dapat digunakan untuk proses verifikasi serta tindak lanjut sesuai ketentuan yang berlaku.</p></div><div className="flex justify-between border-t border-zinc-200 pt-5"><button onClick={() => setPage("evidence")} className="border border-zinc-300 px-5 py-3 text-sm font-semibold uppercase tracking-[0.16em] text-zinc-600">Kembali</button><button onClick={() => setPage("confirmation")} className="bg-[#0b3042] px-5 py-3 text-sm font-semibold uppercase tracking-[0.16em] text-white">Kirim Pengaduan</button></div></div><SideHelp title="Setelah dikirim" icon={ShieldCheck} items={["Sistem menerbitkan nomor tiket.", "Pelapor menerima email konfirmasi.", "Bappebti melakukan verifikasi awal.", "Pengaduan diteruskan ke pihak terkait bila memenuhi kriteria."]} /></div></PageShell>; }
function Confirmation({ setPage }) { return <PageShell setPage={setPage} step={5} title="Pengaduan berhasil dikirim" subtitle="Simpan nomor tiket berikut untuk memantau perkembangan pengaduan Anda."><div className="mx-auto max-w-3xl border border-zinc-200 bg-white p-8 text-center shadow-sm"><div className="mx-auto flex h-16 w-16 items-center justify-center rounded-full bg-emerald-50 text-emerald-700"><CheckCircle2 className="h-9 w-9" /></div><h2 className="mt-5 text-2xl font-semibold text-zinc-800">Terima kasih. Pengaduan Anda telah diterima.</h2><p className="mt-3 text-sm leading-6 text-zinc-600">Nomor tiket dan ringkasan pengaduan telah dikirim ke email/nomor HP yang Anda daftarkan.</p><div className="mx-auto mt-6 max-w-md bg-[#0b3042] p-5 text-white"><p className="text-xs uppercase tracking-[0.2em] text-white/70">Nomor Tiket</p><p className="mt-2 font-mono text-2xl font-semibold">BPP-2026-000184</p></div><div className="mt-7 flex justify-center gap-3"><button className="inline-flex items-center gap-2 border border-zinc-300 px-5 py-3 text-sm font-semibold uppercase tracking-[0.16em] text-zinc-700"><Download className="h-4 w-4" /> Unduh Bukti</button><button onClick={() => setPage("tracking")} className="inline-flex items-center gap-2 bg-[#0b3042] px-5 py-3 text-sm font-semibold uppercase tracking-[0.16em] text-white"><Eye className="h-4 w-4" /> Lihat Status</button></div></div></PageShell>; }
function TimelineItem({ item, last }) { return <div className="flex gap-4"><div className="flex flex-col items-center"><div className={`flex h-9 w-9 items-center justify-center rounded-full ${item.done ? "bg-emerald-50 text-emerald-700" : "bg-zinc-100 text-zinc-400"}`}>{item.done ? <CheckCircle2 className="h-5 w-5" /> : <Clock3 className="h-5 w-5" />}</div>{!last && <div className="h-12 w-px bg-zinc-200" />}</div><div><p className="font-semibold text-zinc-800">{item.title}</p><p className="mt-1 text-sm leading-6 text-zinc-600">{item.note}</p><p className="mt-1 text-xs text-zinc-400">{item.time}</p></div></div>; }
function Tracking({ setPage }) { return <Layout setPage={setPage}><main className="mx-auto max-w-7xl px-6 py-10"><div className="mb-7"><h1 className="text-3xl font-semibold tracking-tight text-zinc-800">Cek status pengaduan</h1><p className="mt-2 max-w-3xl text-sm leading-6 text-zinc-600">Masukkan nomor tiket dan email/no. HP pelapor untuk melihat perkembangan penanganan.</p></div><div className="grid grid-cols-1 gap-7 lg:grid-cols-12"><div className="border border-zinc-200 bg-white p-7 lg:col-span-4"><FormField label="Nomor tiket" placeholder="BPP-2026-000184" /><div className="mt-5"><FormField label="Email / No. HP" placeholder="andi@email.com" /></div><button className="mt-6 w-full bg-[#0b3042] px-5 py-3 text-sm font-semibold uppercase tracking-[0.16em] text-white">Cek Status</button><p className="mt-4 text-xs leading-5 text-zinc-500">Untuk keamanan, sebagian detail hanya ditampilkan setelah data cocok dengan identitas pelapor.</p></div><div className="border border-zinc-200 bg-white p-7 lg:col-span-8"><div className="flex flex-wrap items-start justify-between gap-4 border-b border-zinc-200 pb-5"><div><p className="font-mono text-sm text-zinc-500">BPP-2026-000184</p><h2 className="mt-1 text-2xl font-semibold text-zinc-800">Penarikan dana belum diterima</h2><p className="mt-2 text-sm text-zinc-500">Platform: PT Bursa Digital Nusantara</p></div><div className="flex gap-2"><Badge tone="amber">Dalam Proses</Badge><Badge tone="pale">Sisa SLA 18 jam</Badge></div></div><div className="mt-6 space-y-6">{sampleTimeline.map((item, idx) => <TimelineItem key={item.title} item={item} last={idx === sampleTimeline.length - 1} />)}</div><div className="mt-7 border border-[#d7e4e8] bg-[#eef4f6] p-5"><p className="flex items-center gap-2 text-sm font-semibold text-[#0b3042]"><AlertCircle className="h-4 w-4" /> Informasi untuk pelapor</p><p className="mt-2 text-sm leading-6 text-zinc-600">Saat ini pengaduan sedang menunggu tanggapan dari pelaku usaha terkait. Anda akan menerima notifikasi saat terdapat pembaruan atau permintaan klarifikasi.</p></div></div></div></main></Layout>; }
function Suggestion({ setPage }) { return <Layout setPage={setPage}><main className="mx-auto max-w-4xl px-6 py-10"><h1 className="text-3xl font-semibold tracking-tight text-zinc-800">Kritik & Saran</h1><p className="mt-2 text-sm leading-6 text-zinc-600">Gunakan halaman ini untuk mengirimkan masukan umum terkait layanan Bappebti.</p><div className="mt-7 border border-zinc-200 bg-white p-7"><div className="grid grid-cols-1 gap-5 md:grid-cols-2"><FormField label="Nama" placeholder="Nama Anda" /><FormField label="Email / No. HP" placeholder="Kontak yang dapat dihubungi" /><FormField wide label="Topik masukan" placeholder="Pilih topik" select /><FormField wide textarea label="Isi kritik / saran" placeholder="Tuliskan masukan Anda di sini." /></div><div className="mt-7 flex justify-end border-t border-zinc-200 pt-5"><button onClick={() => setPage("landing")} className="bg-[#0b3042] px-5 py-3 text-sm font-semibold uppercase tracking-[0.16em] text-white">Kirim Masukan</button></div></div></main></Layout>; }
function Guide({ setPage }) { return <Layout setPage={setPage}><main className="mx-auto max-w-5xl px-6 py-10"><h1 className="text-3xl font-semibold tracking-tight text-zinc-800">Panduan memilih layanan</h1><div className="mt-7 grid grid-cols-1 gap-6 md:grid-cols-2"><div className="border border-zinc-200 bg-white p-7"><h2 className="text-xl font-semibold text-zinc-800">Gunakan Pengaduan Resmi bila...</h2><div className="mt-5 space-y-3"><Checklist text="Ada masalah transaksi, dana, akun, layanan, atau dugaan pelanggaran." /><Checklist text="Anda membutuhkan nomor tiket dan tindak lanjut resmi." /><Checklist text="Ada pihak platform/pelaku usaha yang perlu dimintakan tanggapan." /></div><button onClick={() => setPage("identity")} className="mt-7 bg-[#0b3042] px-5 py-3 text-sm font-semibold uppercase tracking-[0.16em] text-white">Buat Pengaduan</button></div><div className="border border-zinc-200 bg-white p-7"><h2 className="text-xl font-semibold text-zinc-800">Gunakan Kritik & Saran bila...</h2><div className="mt-5 space-y-3"><Checklist text="Anda ingin memberi masukan tentang layanan atau informasi publik." /><Checklist text="Tidak ada kasus transaksi spesifik yang perlu diselesaikan." /><Checklist text="Tidak membutuhkan verifikasi formal atau SLA penanganan kasus." /></div><button onClick={() => setPage("suggestion")} className="mt-7 border border-[#0b3042] px-5 py-3 text-sm font-semibold uppercase tracking-[0.16em] text-[#0b3042]">Kirim Masukan</button></div></div></main></Layout>; }
function App() { const [page, setPage] = useState("landing"); const screen = useMemo(() => { if (page === "service") return <ServiceType setPage={setPage} />; if (page === "identity") return <Identity setPage={setPage} />; if (page === "complaint") return <ComplaintDetail setPage={setPage} />; if (page === "evidence") return <EvidenceUpload setPage={setPage} />; if (page === "review") return <ReviewSubmit setPage={setPage} />; if (page === "confirmation") return <Confirmation setPage={setPage} />; if (page === "tracking") return <Tracking setPage={setPage} />; if (page === "suggestion") return <Suggestion setPage={setPage} />; if (page === "guide") return <Guide setPage={setPage} />; return <Landing setPage={setPage} />; }, [page]); return <motion.div initial={{ opacity: 0 }} animate={{ opacity: 1 }} className="min-h-screen">{screen}</motion.div>; }

createRoot(document.getElementById("root")).render(<App />);
